services:
  - type: web
    name: hrm-fastapi-app
    env: python
    repo: https://github.com/Vishwbstwde1302/HRM-system
    branch: main
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host=0.0.0.0 --port=10000"
    envVars:
      - key: PORT
        value: 10000
